apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-app-config
  namespace: quiz-app
  labels:
    app: quiz-app
data:
  SPRING_PROFILES_ACTIVE: "default"
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_EXAMPLE: "DEBUG"
