apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
  namespace: quiz-app
  labels:
    app: quiz-app
spec:
  type: NodePort
  selector:
    app: quiz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
