name: Quiz App CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Code Quality Check (Checkstyle)
        run: ./mvnw validate

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Dependency Vulnerability Scan (SCA)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL'
          exit-code: 1

      - name: Build Docker image
        run: docker build -t quiz-app:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: quiz-app:latest
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name quiz quiz-app:latest
          sleep 15
          curl http://localhost:8080 || exit 1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker tag quiz-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/quiz-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quiz-app:latest
